package com.ece.bot.common.error;

public enum ResponseError {

    //CREATION CARDS ERRORS
    EMPTY_CARD_NAME,
    NOT_UNIQUE_CARD_NAME,
    EMPTY_CARD_TYPE,
    EMPTY_CARD_IMAGE_GUID,
    IMAGE_GUID_IS_EMPTY,
    EMPTY_CARD_INFO,
    EMPTY_CARD_LEVEL_MAP,
    NOT_ALL_LANGUAGES_IN_INFO,
    EMPTY_INFO_TEXT,
    EMPTY_NAME_AND_DESCRIPTION,
    EMPTY_NAME_IN_LANGUAGES_MAP,
    EMPTY_DESCRIPTION_IN_LANGUAGES_MAP,
    EMPTY_MAX_LEVEL,
    CARD_LEVEL_MAP_NOT_CONTAINS_MAX_LEVEL,
    ZERO_OR_NEGATIVE_LEVELS,
    INVALID_LEVELS_SEQUENCE,
    EMPTY_CARD_POWER,
    NEGATIVE_CARD_POWER,
    EMPTY_CARD_PRICE,
    NEGATIVE_CARD_PRICE,
    EMPTY_CARD_ID,
    CARD_NOT_FOUND,
    CARD_ALREADY_BOUGHT,

    //FILE ERRORS
    FILE_IS_EMPTY,
    ERROR_WHILE_SAVING_FILE,
    FILE_NOT_FOUND,


    //BALANCE_ERRORS
    BALANCE_ERROR_TRY_LATER,
    NOT_ENOUGH_MONEY,


    //USER ERRORS
    USER_NOT_FOUND,
    INVALID_USER_STATE_MOVE,

    //INTSTANCE ERRORS
    CANT_UPGRADE_BUY_YET
}
